### ISSUE TITLE
router管理path不能自定义

### ISSUE THREAD

**Issue by Bamboo742** [wxlite-plus/mp-router#1]
就是我看了一下routerParase里面的封装，默认是 /pages/${name}/index,不可以获取的，初始化的routes的path么?

**Comment by Jack-Lo** [comment]
优先是从routes匹配的，匹配不到才是`/pages/${name}/index`，如果没有生效，麻烦查看一下routes配置是否正确或者router的name是否正确指定，如果没有解决问题，麻烦贴一下相关代码~

**Comment by Bamboo742** [comment]
请不要默认，路由设置必须匹配，不然你这样子的话，我很排查原因

**Comment by Bamboo742** [comment]
可以考虑不匹配，直接error信息

**Comment by Jack-Lo** [comment]
`/pages/${name}/index`规则是为了规范目录结构，提供一种便于维护的方式，如果不适用于你的项目，可以手动修改`routerParase`，比如将`/pages/${name}/index`改为`/pages/${name}`。

**Comment by Bamboo742** [comment]
.....

**Comment by Bamboo742** [comment]
关闭吧，我懂你的意思。但....
